[package]
name = "dsa-queue"
version = "0.0.1"
edition = "2024"
publish = false
resolver = "2"

[dependencies]
tokio = { workspace = true }
dashmap = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }